### ISSUE TITLE
Issues with artifact.io rate limiting

### ISSUE THREAD

**Issue by sam-cgr** [FairwindsOps/nova#102]
Does anyone have issues around the rate limiting given a large number of helm charts? Is there a way to filter out which helm charts are being searched for?

**Comment by sudermanjr** [comment]
There have been some reports of issues with rate limiting in large environments. Hopefully https://github.com/FairwindsOps/nova/issues/94 will help, but we don't have a perfect solution just yet. 

One option is to avoid polling artifact hub and use a config file that specifies the repositories you know you are using instead. I realize that's not a perfect solution, but it does provide a workaround.

**Comment by sam-cgr** [comment]
@sudermanjr thanks for that good idea.
