### ISSUE TITLE
Nova find - could not detect helm 3 charts

### ISSUE THREAD

**Issue by cmodi-cogito** [FairwindsOps/nova#103]
### What happened?

I have helm version - v3.3.1 and able to list helm releases in cluster
When I run nova command, I am getting this error.

`$ nova find`

root.go:207] error getting helm releases: could not detect helm 3 charts: list: failed to list: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 1; INTERNAL_ERROR; received from peer

### What did you expect to happen?

It should run as expected to list helm chart versions

### How can we reproduce this?

I have helm version - v3.3.1 and able to list helm releases in cluster
When I run nova command, I am getting this error.

`$ nova find`

root.go:207] error getting helm releases: could not detect helm 3 charts: list: failed to list: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 1; INTERNAL_ERROR; received from peer

### Version

3.0.2

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cmodi-cogito** [comment]
@sudermanjr ^^

**Comment by sudermanjr** [comment]
Are there a large number of helm release secrets in the cluster?

The version of helm is possibly an issue here, but it shouldn't be. We are using the helm libraries from somewhere around 3.8, so 3.3 (which was presumably used to create these releases) may be quite behind.

**Comment by nikskiz** [comment]
I am getting the same error, and when I run in verbose mode I get the following

```
I1125 10:45:50.145174   15084 round_trippers.go:553] GET https://xxxx.eks.amazonaws.com/api/v1/secrets?labelSelector=owner%3Dhelm 200 OK in 4523 milliseconds
I1125 10:45:50.145257   15084 round_trippers.go:570] HTTP Statistics: DNSLookup 101 ms Dial 5 ms TLSHandshake 10 ms ServerProcessing 4405 ms Duration 4523 ms
I1125 10:45:50.145291   15084 round_trippers.go:577] Response Headers:
I1125 10:45:50.145331   15084 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: xxxx
I1125 10:45:50.145366   15084 round_trippers.go:580]     Date: Thu, 24 Nov 2022 23:45:50 GMT
I1125 10:45:50.145393   15084 round_trippers.go:580]     Audit-Id: xxx
I1125 10:45:50.145427   15084 round_trippers.go:580]     Cache-Control: no-cache, private
I1125 10:45:50.145461   15084 round_trippers.go:580]     Content-Type: application/json
I1125 10:45:50.145488   15084 round_trippers.go:580]     Vary: Accept-Encoding
I1125 10:45:50.145526   15084 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: xxxx
I1125 10:46:45.839899   15084 request.go:971] Stream error http2.StreamError{StreamID:0x1, Code:0x2, Cause:(*errors.errorString)(0xc00007ff60)} when reading response body, may be caused by closed connection.
F1125 10:46:45.840053   15084 root.go:262] error getting helm releases: could not detect helm 3 charts: list: failed to list: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 1; INTERNAL_ERROR; received from peer
```

I have masked some sensitive values with `xxx`

Based on the request I was able to use kubectl and return the secrets.
`kubectl get secrets -l owner=helm -A`
