### ISSUE TITLE
`nova --containers` recommends wrong image

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/nova#122]
### What happened?

ran `nova --containers` and it found `docker.io/bitnami/jenkins:2.249.3-debian-10-r6`. It recommended tag `2.332.3` instead of `2.332.3-debian-11-r6`.

Tricky situation but I think we should be able to parse it.

### What did you expect to happen?

Recommend a debian tag

### How can we reproduce this?

Install `docker.io/bitnami/jenkins:2.249.3-debian-10-r6` and run `nova --containers`

### Version

3.2.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
This was discussed in detail during the development of this feature, and it was decided to go this route due to the extremely inconsistent use of non-semver tags

**Comment by sudermanjr** [comment]
Please see the detailed description in https://github.com/FairwindsOps/nova/pull/95, as well as the `--show-non-semver` flag
