### ISSUE TITLE
Support install via asdf

### ISSUE THREAD

**Issue by kr3cj** [FairwindsOps/nova#16]
**Is your feature request related to a problem? Please describe.**
Currently, I can install Nova a few different ways (e.g. `go` or `homebrew`). It would be nice to also support installation via an `asdf` plugin.

**Describe the solution you'd like**
Create an `asdf` plugin for Nova. See their [docs](https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md) for more info.

**Describe alternatives you've considered**
Installing via homebrew or go. However, homebrew installation is system wide and doesn't fit into our version management workflows.

**Additional context**
Other FairwindsOps tools also support installation via `asdf` (e.g. Pluto). For background, we rely heavily on asdf's `.tool-version` files to manage our binary tool versions in local code. For us, having `nova` work into the same workflow would make it easier for us to work with and more likely to adopt.

**Comment by kr3cj** [comment]
FYI [asdf-vm/asdf-plugins/pull/277](https://github.com/asdf-vm/asdf-plugins/pull/277) merged

**Comment by sudermanjr** [comment]
Thanks!
