### ISSUE TITLE
Find containers - timeout

### ISSUE THREAD

**Issue by jchambrin** [FairwindsOps/nova#169]
### What happened?

When I launch `nova find --containers --show-errored-containers --format table` on my Kubernetes clusters, I get the following error : `Get "https://index.docker.io/v2/": context deadline exceeded` 

### What did you expect to happen?

No timeout

### How can we reproduce this?

Launch `nova find --containers --show-errored-containers --format table` on a cluster with a lot of pods

### Version

Version:3.4.0 Commit:e73dbcef4e82ebb2a17137e9e22dee8ab073f40a

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

In the following function 
```
func handleContainers(kubeContext string) (*output.ContainersOutput, error) {
	// Set up a context we can use to cancel all operations to external container registries if we need to
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
```
The timeout seems to be the problem here. If we change it for 100 seconds for example, everything is working

**Comment by treyhendon** [comment]
Small bump on this.  Is there any way that the timeout value could be an env var or config we could pass into Nova?  We are running into issues with the container timeout because we have a very large cluster that is being evaluated.
