### ISSUE TITLE
Find always outputs in json

### ISSUE THREAD

**Issue by ndlanier** [FairwindsOps/nova#189]
### What happened?

Running nova find and nova find --wide always output in json

### What did you expect to happen?

Expected output to be in a readable format (or prettyfied)

### How can we reproduce this?

install via brew
run nova find or nova find --wide

### Version

3.6.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
I think you need `nova find --format table --wide`

**Comment by ndlanier** [comment]
That worked thank you
