### ISSUE TITLE
Ability to scan helm charts located in local file system

### ISSUE THREAD

**Issue by devmechanic** [FairwindsOps/nova#200]
**Is your feature request related to a problem? Please describe.**
We are deploying helm charts via ArgoCD and this approach doesn't create release information that nova can look for.

**Describe the solution you'd like**
We are keeping helm charts in git repository. It would be great if nova can have additional option to scan local folders with helm charts. It could also scan all subfolders recursively.

**Describe alternatives you've considered**
Nothing at this point.

**Additional context**
This is a folder structure as an example:
\helm-chars\dev\chart01
\helm-chars\dev\chart02
\helm-chars\prod\chart01
\helm-chars\prod\chart01
etc.

**Comment by sudermanjr** [comment]
I think it's a great idea. Could tie together nicely with https://github.com/FairwindsOps/nova/issues/62 as well

**Comment by devmechanic** [comment]
Yes; any way of scanning helm charts beyond running cluster would be great.
