### ISSUE TITLE
Allow to configure an ignore list of charts that don't need checking

### ISSUE THREAD

**Issue by deiga** [FairwindsOps/nova#206]
**Is your feature request related to a problem? Please describe.**
We have a lot of private charts installed and we don't need Nova telling us that they don't have updates or even worse, they might match names that exist in artifacthub and then Nova claims they have updates, so we would like to tell Nova what charts to ignore. Sometimes Nova throws an error like `Error getting artifacthub package repos: failed to search for packages for term broca
` for some of our private packages, which this would solve as well

**Describe the solution you'd like**
Add a CLI flag and a Config file option to add a list of ignored Chart names

**Comment by sudermanjr** [comment]
Seems like it would fairly straightforward. Would you envision ignoring release names, chart names, or both or either?

**Comment by deiga** [comment]
For my use-case I currently only care about ignoring chart names, but I can see why you might want to ignore specific release names. But I think they should be separate options

**Comment by sudermanjr** [comment]
I agree as well, separate options would be better. Is this something you would want to contribute?

**Comment by RohitKochhar** [comment]
I'll handle this!

**Comment by RohitKochhar** [comment]
I've added some code in the [above PR](https://github.com/FairwindsOps/nova/pull/252) to add this functionality in. If you could assign this issue to me until it is complete to avoid having multiple people working on it in parallel, that would be great!
