### ISSUE TITLE
Sometimes Nova fails to complete running because of not finding private Charts in ArtifactHub

### ISSUE THREAD

**Issue by deiga** [FairwindsOps/nova#207]
### What happened?

We have a lot of private Helm Charts that don't exist in AH and mostly that works fine with Nova. Sporadically Nova quits unexpectedly with the following message: `Error getting artifacthub package repos: failed to search for packages for term <chart name>`

### What did you expect to happen?

For Nova to mark the Chart as not-outdated and continue to process the next Chart.

### How can we reproduce this?

I don't know

### Version

3.6.2

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Interesting. I wonder if we just logged the error but didn't return it [here](https://github.com/FairwindsOps/nova/blob/a55e37fa76fe9012585dd896a25a1883cf1247c6/pkg/helm/artifacthub.go#L276-L281) if that would handle. I'm unclear on what the other consequences would be though

**Comment by deiga** [comment]
@sudermanjr This seems to happen to public charts as well! Got this error today 
```
F0311 17:39:38.659089      17 root.go:272] Error getting artifacthub package repos: failed to search for packages for term ingress-nginx
```

I wonder if this is some rate-limiting from ArtifactHub? If it is, then it could be solved by adding some checks and waits for something like that

**Comment by sudermanjr** [comment]
This should be fixed by the rate-limiting fix that we implemented last week.
