### ISSUE TITLE
Add a sort option to Nova, so that we would --include-all and sort all outdated packages to the start or end

### ISSUE THREAD

**Issue by deiga** [FairwindsOps/nova#208]
**Is your feature request related to a problem? Please describe.**
When running Nova with --include-all an --format=table the outdated Charts are mixed with non-outdated ones, since the output is sorted by Namespace.

**Describe the solution you'd like**
We would like to be able to sort by the `Old` field in ASC or DESC order.

**Comment by sudermanjr** [comment]
Seems like a great idea. Probably need both a `--sort-by` and a `--sort-order` or something like that so that we could sort on any column header. We would love to see a pull request from the community on this!

**Comment by AbdulAhadAkhter** [comment]
Would love to give this a whirl! I'll try whipping something up this weekend!
