### ISSUE TITLE
Nova times out when fetching ridiculous number of tags

### ISSUE THREAD

**Issue by joshfrench** [FairwindsOps/nova#234]
**Is your feature request related to a problem? Please describe.**
Nova reliably times out when looking up containers with many tags. Example: [calico/node](https://quay.io/repository/calico/node?tab=tags) has ~9800 tags and I've never successfully gotten Nova to complete a lookup. 

**Describe the solution you'd like**
Possibly a flag to limit the number of tags returned, although this assumes the tags are returned in reverse chronological order. I'm not sure if that's a safe assumption or how this would work without that guarantee. 

**Describe alternatives you've considered**
Alternatively, a way to specify a (much) longer timeout (see #169).

**Comment by sudermanjr** [comment]
Thanks for the report! I believe both options are viable, and we could definitely implement both. 

I _think_ we can get the registry to give us a chronological list, but I'm not certain about that. If not, the timeout could be helpful as well.

Is this something you would like to tackle?

**Comment by joshfrench** [comment]
I'm happy to at least take a first pass and kick it back if I get lost.

**Comment by sudermanjr** [comment]
Awesome! Thanks. Feel free to ping us here or in the community slack with any questions.
