### ISSUE TITLE
Support OCI chart repositories

### ISSUE THREAD

**Issue by Gui13** [FairwindsOps/nova#275]
**Is your feature request related to a problem? Please describe.**

OCI is supported by Helm since [Jan 2022](https://github.com/helm/helm/releases/tag/v3.8.0).

This is becoming the main distribution channel for Helm charts, since it piggybacks on Docker registries and facilitates scanning & policies applications. 
As of today, Nova cannot use OCI repositories, since it depends on the package list of ChartMuseum format. It would be a good step 

Some popular registries (harbor for instance) are migrating to OCI-only support, and thus cannot be used when scanning with the current Nova software.

**Describe the solution you'd like**

I would like nova to implement the ability to scan for semver versions of charts in an OCI repository. It is possible already using the Helm command line like this:

`helm show crds oci://my-repository_url/my-chart` which shows the latest helm chart found on the OCI repo

**Describe alternatives you've considered**

There are many helm chart "exporters" out there, but none of them has proper OCI support. Even [helm-exporter](https://github.com/sstarcher/helm-exporter) has closed his issue about this.

**Additional context**

Note that the OCI spec doesn't specify a "search" axiom ([it is in the works](https://github.com/opencontainers/distribution-spec/issues/222), or least identified).

**Comment by sudermanjr** [comment]
Agreed, this would be a very good thing to add to Nova as OCI becomes common.

**Comment by Gui13** [comment]
@sudermanjr the issue is being closed as completed, without any commit indicating that the work has been done. 

Did you guys implement it in a "paid" version?

I am actually interested in using it, even commercially.

**Comment by evandam** [comment]
I'd love to see this added - it's getting harder to be able to use Nova to track available upgrades as more Helm chart providers shift to OCI images :eyes:
