### ISSUE TITLE
Make Docker Image Public Available

### ISSUE THREAD

**Issue by Skaronator** [FairwindsOps/nova#37]
**Is your feature request related to a problem? Please describe.**
Instead of installing many small tools on my local machine I often just use the container image since its faster to update or even has auto update when you use the latest tag. 

I can see that there is already exist a Dockerfile in this repo but the Image doesn't seem to be public available.

**Describe the solution you'd like**
Push the Container Image to Docker Hub or Gitlab Container Registry.

Due to the Docker Pull limits I suggest the Gitlab Container Registry if you don't want to push to both.

**Comment by Skaronator** [comment]
This would probably also help Windows User since they can run Containers in Windows.

**Comment by sudermanjr** [comment]
The image is available at https://quay.io/repository/fairwinds/nova

We do not support multi-arch builds just yet.
