### ISSUE TITLE
Ability to specify a namespace

### ISSUE THREAD

**Issue by ninoamine** [FairwindsOps/nova#38]
**Is your feature request related to a problem? Please describe.**
Nova does two things according to the README:
Nova scans your cluster for installed Helm charts, then cross-checks them against all known Helm repositories

I'd like to be able to use Nova by namespace.

**Describe the solution you'd like**
Add an option as -n <namespace>

**Comment by evgkrsk** [comment]
Nova needs cluster-scope secrets list permission in RBAC, which leads to inability to work with typical OpenShift cluster:

```
F0706 15:33:40.394022   16638 root.go:269] error getting helm releases: could not detect helm 3 charts: list: failed to list: secrets is forbidden: User "foo.bar" cannot list secrets at the cluster scope: no RBAC policy matched
```
