### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by MrKrabat** [FairwindsOps/nova#63]
**Is your feature request related to a problem? Please describe.**
I want to know if helm chart dependencies have updates.

As an example, the helm chart bitnami/keycloak also deploys bitnami/postgresql as a dependency. The version tag `version: 10.x.x` allows postgresql to get updates.
https://github.com/bitnami/charts/blob/master/bitnami/keycloak/Chart.yaml

**Describe the solution you'd like**
A new output column that indicates whether dependency updates are available.

**Describe alternatives you've considered**
Maybe list the dependencies as a separate row.

**Comment by sudermanjr** [comment]
@MrKrabat That's an interesting idea, thanks for sharing! This seems like it might be possible, so I have marked it as an enhancement.

**Comment by dhduvall** [comment]
I'd really love to see this, too. I have some private charts that are simply wrappers around public ones, and while I don't really need to be told about updates to the private ones, I do need to know when their public dependencies are out of date.

**Comment by dhduvall** [comment]
I can see that this would be a substantial change, though, since `nova` outputs `Release`s, and `helm` doesn't treat dependencies as `Release`s.

**Comment by sudermanjr** [comment]
Sounds like a valid use-case to me, I like it! Would happily support a community contribution on this too!

**Comment by 26tanishabanik** [comment]
@sudermanjr , I would like to contribute to this issue, seems like a very interesting use-case.
It would be great, if you can point me in the right direction in the repo, thanks.

**Comment by antoineozenne** [comment]
It could be great to have this feature. Most of the time, when we want to use an official chart, we encapsulate it in a custom chart in order to add some elements necessary for our Cloud Provider infrastructure (Key Vault, IAM, etc.). So nova can't work in this case.
