### ISSUE TITLE
consider supporting --context or --kube-context

### ISSUE THREAD

**Issue by anapsix** [FairwindsOps/nova#7]
**Is your feature request related to a problem? Please describe.**
there appears to be no way to pick a kubeconfig context, which forces user to separate specific contexts into individual kubeconfigs

**Describe the solution you'd like**
support `--context` or `--kube-context` cli option to select appropriate context from kubeconfig

**Describe alternatives you've considered**
one can generate a separate kubeconfig with the following
```
kubectl --context=${context_name} config view --minify --flatten
```

**Comment by rbren** [comment]
You should be able to choose your context using `kubectl config use-conext` - does that not work for you?

**Comment by anapsix** [comment]
you're right, it works  
imho, it would be awesome to support something like `--kube-context` (like helm does) to do it in one go

**Comment by sudermanjr** [comment]
I also think that would be a valid feature request.
