### ISSUE TITLE
The "poll-helm-hub" and "url" features in the config file no longer work

### ISSUE THREAD

**Issue by ctavian** [FairwindsOps/nova#71]
### What happened?

Hello, After the Nova 3.0.0 update, the "url:" and "poll-helm-hub:" features are no longer present.
As a result, I find myself with versions of charts in nightly-build and not in release version or tags that no longer corresponds to the original convention : example for "kubed".

Also, Artifacthub does not have the set of available helms : example for "csi-secrets-store".

Example output (2.3.0) :

```

Release Name                    Installed    Latest      Old      Deprecated

vector-aggregator               0.18.1         0.21.2      true     false
csi-secrets-store                 0.1.0          1.0.1         true     false
kubed                                    v0.12.0      v0.13.1     true     false

```

And 

Example output (3.0.0) : 

```
Release Name                    Installed           Latest                                        Old      Deprecated
============                 =========    ======                                     ===      ==========

kubed                                    v0.12.0           0.13.1                                         true     false
vector-aggregator               0.18.1              0.20.0-nightly-2022-01-04    true     false

```

In 3.0.0 output, we don't have the csi-secrets-store, the vector-aggregator have a nightly build verison and kubed change the tag convention 
 

### What did you expect to happen?

After run the command `nova find --config=config.ymlà, I expect to have a result that corresponds to a check between the urls charts of my config file and the currently installed charts in my cluster K8S.

### How can we reproduce this?

Use the config file : 

```
#config.yml

poll-helm-hub: false

url:
  - https://charts.appscode.com/stable
  - https://helm.vector.dev
  - https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
```

And run this command on nova 3.0.0 : 

```
nova find --config=config.yml
```

Result : 

```
Release Name                    Installed    Latest                       Old      Deprecated
============                    =========    ======                       ===      ==========
kubed                           v0.12.0      0.13.1                       true     false
vector-aggregator               0.18.1       0.20.0-nightly-2022-01-04    true     false
```

And with the 2.3.0 version : 

```
Release Name                    Installed    Latest     Old      Deprecated
kubed                                 v0.12.0      v0.13.1    true      false
csi-secrets-store               0.1.0         1.0.1        true      false
vector-aggregator             0.18.1       0.21.2      true      false
```

### version

3.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klis** [comment]
I would like to add that ArtifactHub has older versions of some charts. For example, `kubernetes-replicator` has version `1.0.15` on [the ArtifactHub](https://artifacthub.io/packages/helm/jenkins-x/kubernetes-replicator), and in the GitHub repo, it is `2.7.3` - [link to the Charts.yaml ](https://github.com/mittwald/kubernetes-replicator/blob/master/deploy/helm-chart/kubernetes-replicator/Chart.yaml)

**Comment by lucasreed** [comment]
@ctavian and @klis thanks again for your input here. I've opened PR #74 if you would want to test those out. If you have a working go install on your workstation you can simply pull down this repo + that branch and run `make build` and then use `./nova` like you would normally.

One thing of note is that `poll-helm-hub` is gone for good but is now replaced by `poll-artifacthub`. Please comment on that PR if the functionality still doesn't fit your usecases.

**Comment by ctavian** [comment]
@lucasreed, Thanks, it works! :)

**Comment by klis** [comment]
@lucasreed & @ctavian are you sure about the logic? 
I tried it and looks like that when I specify the URL, only that URL is shown in the output. For example, if I run the default options I get a list of "all" charts that are available on ArtifactHub. Pay attention to the `kubernetes-replicator` versions. 
```
> ./nova find
Release Name             Installed    Latest     Old      Deprecated
============             =========    ======     ===      ==========
cert-manager             v1.7.1       1.7.1      false    false
harbor                   1.7.1        1.8.1      true     false
operator                 0.6.0        0.6.0      false    false
kubernetes-replicator    2.7.3        1.0.15     false    false
minio-operator           4.3.7        4.3.7      false    false
kube-prometheus-stack    18.1.0       32.2.1     true     false
loki                     2.6.1        2.6.1      false    false
prometheus-adapter       2.17.0       3.0.2      true     false
traefik                  10.14.1      10.14.1    false    false
```

Now, I do the same thing, but only I add 2 flags, one to still poll ArtifactHub, another one to poll `kubernetes-replicator` chart. 
I only got results for the `kubernetes-replicator` chart. I would love to get all the results, only that charts specified in the `--url` have precedence over the ArtifactHub. 
```
> ./nova find --url=https://helm.mittwald.de --poll-artifacthub=true
Release Name             Installed    Latest    Old      Deprecated
============             =========    ======    ===      ==========
kubernetes-replicator    2.7.3        2.7.3     false    false
```

And yes, I know that I can specify all the URLs, but if I plug `nova` in the CI system, then I need to maintain a config file, or the full command for `nova find`

**Comment by ctavian** [comment]
Hello @klis,

I think there might be a problem with the precedence of the value when you use both --url and the poll-artifacthub to true.

In your case, you just want to add new, more recent repositories, see missing from artifacthub.

However, how will nova behave to choose the version between what is provided by the URL and by artifacthub.

**Comment by klis** [comment]
So, what I would do is that if the chart is provided via URL then just skip artifacthub. This still means that if the provided URL has an older version then the artifacthub nova will show the old version (kubernetes-replicator example from my previous comment).
If I add `--include-all` flag, nova will list all the Helm charts, but only one will have `Latest` filled. 
Would be nice to have all the data, url and artifacthub? Basically, if the Helm chart that is installed is defined in the URL, then go to that URL, and for that chart skip artifacthub. 

```
> ./nova find --url=https://helm.mittwald.de --poll-artifacthub=true --include-all
Release Name             Installed    Latest    Old      Deprecated
============             =========    ======    ===      ==========
cert-manager             v1.7.1                 false    false
harbor                   1.7.1                  false    false
operator                 0.6.0                  false    false
kubernetes-replicator    2.7.3        2.7.3     false    false
minio-operator           4.3.7                  false    false
kube-prometheus-stack    18.1.0                 false    false
loki                     2.6.1                  false    false
prometheus-adapter       2.17.0                 false    false
traefik                  10.14.1                false    false
```

Maybe I'm going too far, but I would like to see nova do that. I don't know if older versions of nova worked that way since I only recently started to integrate this into our CI workflow.

**Comment by lucasreed** [comment]
In my testing it should work with both `--url` and artifacthub in one run. Could you add the `--v=8` to your command so we have more logging?

**Comment by lucasreed** [comment]
Thanks @klis! I'll try to replicate this locally and go from there.

**Comment by klis** [comment]
> @klis can you try pulling and building after my most recent commit. It was a simple one-line commit that allows a function to return a nil instead of an empty struct. I think that fixes this problem.
> 
> I reproduced your issue locally and after my change it is working as expected.
> 
> Before:
> 
> ```
> > ./nova find --url=https://helm.mittwald.de --poll-artifacthub=true --include-all
> Release Name             Installed    Latest    Old      Deprecated
> ============             =========    ======    ===      ==========
> cert-manager             v1.7.1                 false    false    
> harbor                   1.7.1                  false    false    
> kubernetes-replicator    2.7.3        2.7.3     false    false
> ```
> 
> After:
> 
> ```
> > ./nova find --url=https://helm.mittwald.de --poll-artifacthub=true --include-all
> Release Name             Installed    Latest    Old      Deprecated
> ============             =========    ======    ===      ==========
> cert-manager             v1.7.1       1.7.1     false    false    
> harbor                   1.7.1        1.8.1     true     false    
> kubernetes-replicator    2.7.3        2.7.3     false    false
> ```

It was working, but it looks like artifacthub has some issue currently, so I will try again later. With the CLI flags and with the config file.

**Comment by lucasreed** [comment]
@klis good find! I just pushed up another change that I think captures this case too. Once this is validated I think we're in a good place to merge the PR and cut a release.

**Comment by klis** [comment]
> @klis good find! I just pushed up another change that I think captures this case too. Once this is validated I think we're in a good place to merge the PR and cut a release.

Looks good to me
