### ISSUE TITLE
The CHANGELOG.md is not  update in repo

### ISSUE THREAD

**Issue by ctavian** [FairwindsOps/nova#72]
Hello, 

I noticed that the change log does not have information on new releases (example on breaking changes). 

What do you think ? Should we remove it or add a task in the CI to verify that the CHANGELOG file has been updated before merging.

**Comment by sudermanjr** [comment]
My preference is to remove it and let the goreleaser notes in the release object handle this for us. It's how we did it in our other projects.

@rbren @makoscafee will have to weigh in as CODEOWNERS though.

**Comment by ctavian** [comment]
Ok thank you for your answers, in my opinion, version 3.0.0 created a break on features present in version 2.4.0 (view https://github.com/FairwindsOps/nova/issues/71).

**Comment by sudermanjr** [comment]
@rbren I think we should enforce that PR names for breaking changes should have `[Breaking]` in them. This will make sure they show up in the release notes.
