### ISSUE TITLE
The results are not finding the upstream releases for certain helm repos

### ISSUE THREAD

**Issue by cdestouni-fmp** [FairwindsOps/nova#85]
### What happened?

Ran the nova find cmd on my cluster.

### What did you expect to happen?

Return the helm chart versions I have installed and also the latest versions from each helm-chart repo. I got most new releases back but there were some which did not work.

### How can we reproduce this?

Install the below helm charts on a k8s cluster and run nova find
- sorry-cypress v1.2.0 (https://github.com/sorry-cypress/charts)
- chaos-mesh v2.0.1 (https://github.com/chaos-mesh/charts)

You should see that the Latest column is empty for both.

### Version

0.0.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

FYI - Chaos mesh has no releases published in its Charts repo so wondering if this could be a problem. However sorry-cypress does have releases published.

**Comment by sudermanjr** [comment]
@lucasreed  I looked, and the sorry-cypress chart at least is listed in artifact hub. Not sure what's going on here. https://artifacthub.io/packages/helm/sorry-cypress/sorry-cypress

**Comment by lucasreed** [comment]
@cdestouni-fmp what version of Nova are you using? I see in your PR comment you entered `0.0.1` but that's not a valid release that we put out. If you aren't using v3.0.0 or higher could you upgrade to that? If you are, please include the output from the commands below:

`nova version`

`nova find --wide -v8`

**Comment by cdestouni-fmp** [comment]
@lucasreed I was using an old version 1.0.0 and since then have upgraded to 3.0.2. I tried the command again and it worked the first time round, but since then its been returning error code 429 when trying to reach out to the artifact hub. Guessing i'm blocked for doing too many requests for now. However the issue can be closed because it did locate more versions before I got blocked.
