### ISSUE TITLE
Make it easier to output JSON

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/nova#86]
**Is your feature request related to a problem? Please describe.**
If I want to output JSON, I seem to have to set --output-file. There's no way to output JSON to stdout, or non-json to a file

**Describe the solution you'd like**
Have separate --output-file and --format flags

**Describe alternatives you've considered**
Better documentation of existing behavior

**Additional context**
https://fairwindscommunity.slack.com/archives/C02C608F6E7/p1647604190597329

**Comment by der-ali** [comment]
+1

**Comment by scalp42** [comment]
Agreed, it'd be very useful!

**Comment by nagyzekkyandras** [comment]
+1
